jobs:
- job: main_build
  displayName: 'Main Build'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: Xcode@5
    displayName: 'Build macOS Wrapper'
    inputs:
      actions: 'build'
      configuration: 'Release'
      sdk: 
      xcWorkspacePath: '**/*.xcodeproj'
      destinationPlatformOption: 'macOS'

  - task: PublishBuildArtifacts@1
    displayName: 'Bundle Release'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build/Release/'
      ArtifactName: 'jellyfin-macos-wrapper.zip'
      publishLocation: 'Container'